spring.application.name=walletmanagement


# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/walletdb
spring.datasource.username=visitor
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.s